### ISSUE TITLE
一个报错

### ISSUE THREAD

**Issue by ghost** [idranme/koishi-plugin-music-voice#1]
适配器：OneBot V11 / LiteLoaderQQNT OneBot

报错：
![image](https://github.com/idanran/koishi-plugin-music-downloadvoice-api/assets/115393808/0f93d9e1-c365-41cf-a9ce-d4100a380d10)

```
session Error: Error with request send_private_msg, args: {"user_id":QQ号,"message":[{"type":"record","data":{"file":"http://m801.music.126.net/20240402161250/c182c445853e007bbd7f19f663b20792/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/26540104133/1917/e9fd/bd0d/e5aa9b97cf3ac6a690a0eba48e57ab95.mp3","cache":0}}]}, retcode: 1200
                            at Internal._get (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\types.js:44:15)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Internal.<computed> [as sendPrivateMsg] (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\types.js:84:26)
                            at async OneBotMessageEncoder.flush (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\bot\message.js:94:24)
                            at async OneBotMessageEncoder.send (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:561:5)
                            at async OneBotBot.sendMessage (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:326:22)
                            at async Command.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-music-downloadvoice-api\lib\index.js:205:17)
                            at async Array.<anonymous> (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1137:14)
                            at async Command.execute (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1151:22)
                            at async C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2170:22
```

**Comment by idranme** [comment]
此报错与本插件无关，请向 llonebot 求助。
