### ISSUE TITLE
QQ音乐渠道点歌报错

### ISSUE THREAD

**Issue by okatu-loli** [idranme/koishi-plugin-music-voice#12]
如题，具体报错是：
`12-16 09:45:49 [error] 冷饭酱 | 发生错误 Error: 下载文件失败: Forbidden
    at httpDownload (file:///app/napcat/napcat.mjs:20827:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async uriToLocalFile (file:///app/napcat/napcat.mjs:20872:22)
    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:47772:9)
    at async record (file:///app/napcat/napcat.mjs:47419:8)
    at async Promise.all (index 0)
    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:47709:17)
    at async SendGroupMsg._handle (file:///app/napcat/napcat.mjs:47946:52)
    at async SendGroupMsg.websocketHandle (file:///app/napcat/napcat.mjs:42867:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:43019:21)`

**Comment by okatu-loli** [comment]
网易渠道没问题

**Comment by idranme** [comment]
v1.5.4 是否依然存在该问题？

**Comment by okatu-loli** [comment]
> v1.5.4 是否依然存在该问题？

更新后依然存在问题
![image](https://github.com/user-attachments/assets/187324f3-69b1-4f3c-8957-a9cc5722bb03)


```bash
12-16 17:51:05 [info] 冷饭酱 | 接收 <- 群聊 [一起学习群(***)] [(***)] 点歌 天府
12-16 17:51:06 [info] 冷饭酱 | 发送 -> 群聊 [一起学习群(***)] [(***)] [回复消息 [(***)] 点歌 天府] [图片] 退出选择请发[0,不听了]中的任意内容 ... 45 秒 内， ... 输入歌曲对应的序号
12-16 17:51:10 [info] 冷饭酱 | 接收 <- 群聊 [一起学习群(***)] [(***)] 1
12-16 17:51:10 [info] 冷饭酱 | 发送 -> 群聊 [一起学习群(***)] [(***)] [回复消息 [(***)] 1] 生成语音中…
12-16 17:51:11 [error] 冷饭酱 | 发生错误 Error: 下载文件失败: Forbidden
    at httpDownload (file:///app/napcat/napcat.mjs:20827:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async uriToLocalFile (file:///app/napcat/napcat.mjs:20872:22)
    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:47772:9)
    at async record (file:///app/napcat/napcat.mjs:47419:8)
    at async Promise.all (index 0)
    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:47709:17)
    at async SendGroupMsg._handle (file:///app/napcat/napcat.mjs:47946:52)
    at async SendGroupMsg.websocketHandle (file:///app/napcat/napcat.mjs:42867:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:43019:21)

```

**Comment by Readedd** [comment]
同，上周正常=使用，这周qq音乐渠道也报错，网易正常

如下
2024-12-30 23:18:57 [W] session Error: Error with request send_group_msg, args: {"group_id":976771404,"message":[{"type":"record","data":{"duration":184,"file":"无法正常获取音频文件","cache":0}}]}, retcode: 1200
                            at _Internal._get (/root/koshibot/koishi-app/node_modules/koishi-plugin-adapter-onebot/lib/index.js:119:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
                            at async _Internal.<computed> [as sendGroupMsg] (/root/koshibot/koishi-app/node_modules/koishi-plugin-adapter-onebot/lib/index.js:162:20)
                            at async OneBotMessageEncoder.flush (/root/koshibot/koishi-app/node_modules/koishi-plugin-adapter-onebot/lib/index.js:763:330)
                            at async OneBotMessageEncoder.send (/root/koshibot/koishi-app/node_modules/@satorijs/core/lib/index.cjs:693:5)
                            at async Proxy.sendMessage (/root/koshibot/koishi-app/node_modules/@satorijs/core/lib/index.cjs:423:22)
                            at async _Command.<anonymous> (/root/koshibot/koishi-app/node_modules/koishi-plugin-music-voice/lib/index.js:250:9)
                            at async Array.<anonymous> (/root/koshibot/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1083:14)
                            at async _Command.execute (/root/koshibot/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1097:22)
                            at async /root/koshibot/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2064:22

**Comment by LingLambda** [comment]
同上

**Comment by iAmP1us** [comment]
+1

**Comment by shangxueink** [comment]
> 同，上周正常=使用，这周qq音乐渠道也报错，网易正常
> 
> 如下 2024-12-30 23:18:57 [W] session Error: Error with request send_group_msg, args: {"group_id":976771404,"message":[{"type":"record","data":{"duration":184,"file":"无法正常获取音频文件","cache":0}}]}, retcode: 1200 at _Internal._get (/root/koshibot/koishi-app/node_modules/koishi-plugin-adapter-onebot/lib/index.js:119:11) at process.processTicksAndRejections (node:internal/process/task_queues:105:5) at async _Internal. [as sendGroupMsg] (/root/koshibot/koishi-app/node_modules/koishi-plugin-adapter-onebot/lib/index.js:162:20) at async OneBotMessageEncoder.flush (/root/koshibot/koishi-app/node_modules/koishi-plugin-adapter-onebot/lib/index.js:763:330) at async OneBotMessageEncoder.send (/root/koshibot/koishi-app/node_modules/@satorijs/core/lib/index.cjs:693:5) at async Proxy.sendMessage (/root/koshibot/koishi-app/node_modules/@satorijs/core/lib/index.cjs:423:22) at async _Command. (/root/koshibot/koishi-app/node_modules/koishi-plugin-music-voice/lib/index.js:250:9) at async Array. (/root/koshibot/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1083:14) at async _Command.execute (/root/koshibot/koishi-app/node_modules/@koishijs/core/lib/index.cjs:1097:22) at async /root/koshibot/koishi-app/node_modules/@koishijs/core/lib/index.cjs:2064:22



> 同上



> +1

---


我找了一圈的点歌API，没找到几个有效的。。。


目前星之阁API那边也遇到了一些困难，

对API接口加了key验证，如果共用一个key可以暂时恢复功能，但是估计也很有限。

---

所以考虑加配置项，填写key解决。需要用户自己去群里与机器人发送`/getapiikey`获取秘钥

---

**Comment by shangxueink** [comment]
更新至v1.5.6即可解决

---


关于其中API请求key的部分


星之阁的音乐API的请求key
`默认值是作者自己的哦，如果失效了请你自己获取一个`

请前往 QQ群 905188643
添加QQ好友 3556898686
私聊发送 `/getapikey` 获得你的APIkey以填入此处


---

![image](https://github.com/user-attachments/assets/63092260-8956-4a63-9275-173d18d34c5c)
